language: node_js
node_js:
    - "0.10"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libopencv-dev libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
before_script:
    - npm install -g grunt-cli node-gyp